name: Qt Application Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  # Job for Linux with Clang++
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v4 
        with:
          version: 6.7.3
          
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfluidsynth-dev 
          
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
          
      - name: Configure Qt project with qmake
        run: |
          qmake6 Charts.pro

      - name: Build Qt project with Clang++
        run: |
          export CC=clang
          export CXX=clang++
          make
